// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Panaderia_DonDonas_NET_Core;

#nullable disable

namespace Panaderia_DonDonas_NET_Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230625020617_RelationOneToMany")]
    partial class RelationOneToMany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Panaderia_DonDonas_NET_Core.Entities.Donut", b =>
                {
                    b.Property<int>("Donut_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Donut_Id"), 1L, 1);

                    b.Property<string>("DonutName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Donut_Id");

                    b.ToTable("Donut");
                });

            modelBuilder.Entity("Panaderia_DonDonas_NET_Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Donut_Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfDonuts")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Donut_Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Panaderia_DonDonas_NET_Core.Entities.Order", b =>
                {
                    b.HasOne("Panaderia_DonDonas_NET_Core.Entities.Donut", "Donut")
                        .WithMany("Order")
                        .HasForeignKey("Donut_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donut");
                });

            modelBuilder.Entity("Panaderia_DonDonas_NET_Core.Entities.Donut", b =>
                {
                    b.Navigation("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
